# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import sys

def resource_path(relative_path):
    """PyInstaller ile uyumlu dosya yolu üretir."""
    base_path = getattr(sys, '_MEIPASS', os.path.abspath("."))
    return os.path.join(base_path, relative_path)

class Ui_loginForm(object):
    def setupUi(self, loginForm):
        loginForm.setObjectName("loginForm")
        loginForm.resize(400, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(loginForm.sizePolicy().hasHeightForWidth())
        loginForm.setSizePolicy(sizePolicy)
        loginForm.setMinimumSize(QtCore.QSize(400, 500))
        loginForm.setMaximumSize(QtCore.QSize(400, 500))
        loginForm.setStyleSheet("")
        self.backgroundLabel = QtWidgets.QLabel(loginForm)
        self.backgroundLabel.setGeometry(QtCore.QRect(0, 0, 401, 511))
        self.backgroundLabel.setText("")
        image_path = resource_path("resources/loginbackground.png")
        self.backgroundLabel.setPixmap(QtGui.QPixmap(image_path))  # Düzeltildi
        self.backgroundLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.backgroundLabel.setObjectName("backgroundLabel")
        self.frame = QtWidgets.QFrame(loginForm)
        self.frame.setGeometry(QtCore.QRect(50, 80, 311, 371))
        self.frame.setStyleSheet("\n"
"      background-color: rgba(37, 37, 65, 0.5);\n"
"      border-radius: 20px;\n"
"      border: 2px bold #3A3A5C;\n"
"      box-shadow: 0px 0px 20px rgba(0, 0, 0, 0.5);\n"
"    ")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.usernameL = QtWidgets.QLineEdit(self.frame)
        self.usernameL.setGeometry(QtCore.QRect(20, 160, 269, 51))
        self.usernameL.setMinimumSize(QtCore.QSize(0, 30))
        self.usernameL.setStyleSheet("\n"
"      border: 2px bold #3A3A5C;\n"
"      border-radius: 10px;\n"
"      padding: 10px;\n"
"      font-size: 15px;\n"
"      background: rgba(42, 42, 74, 0.7);\n"
"      color: white;\n"
"    ")
        self.usernameL.setObjectName("usernameL")
        self.passwordL = QtWidgets.QLineEdit(self.frame)
        self.passwordL.setGeometry(QtCore.QRect(20, 229, 269, 51))
        self.passwordL.setMinimumSize(QtCore.QSize(0, 30))
        self.passwordL.setStyleSheet("\n"
"      border: 2px bold #3A3A5C;\n"
"      border-radius: 10px;\n"
"      padding: 10px;\n"
"      font-size: 15px;\n"
"      background: rgba(42, 42, 74, 0.7);\n"
"      color: white;\n"
"    ")
        self.passwordL.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordL.setObjectName("passwordL")
        self.loginL = QtWidgets.QPushButton(self.frame)
        self.loginL.setGeometry(QtCore.QRect(20, 299, 269, 51))
        self.loginL.setMinimumSize(QtCore.QSize(0, 40))
        self.loginL.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        spread:pad,\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #007ACC,\n"
"        stop:1 #005999\n"
"    );\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border: 2px solid #003D66;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        spread:pad,\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #3399FF,\n"
"        stop:1 #007ACC\n"
"    );\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003D66;\n"
"}\n"
"")
        self.loginL.setObjectName("loginL")
        self.logoLabel = QtWidgets.QLabel(self.frame)
        self.logoLabel.setGeometry(QtCore.QRect(20, 20, 271, 81))
        self.logoLabel.setText("")
        image_path = resource_path(self.new_method())
        self.logoLabel.setPixmap(QtGui.QPixmap(image_path))  # Düzeltildi
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setObjectName("logoLabel")

        self.retranslateUi(loginForm)
        QtCore.QMetaObject.connectSlotsByName(loginForm)

    def new_method(self):
        return "resources/logo.png"

    def retranslateUi(self, loginForm):
        _translate = QtCore.QCoreApplication.translate
        loginForm.setWindowTitle(_translate("loginForm", "Form"))
        self.usernameL.setPlaceholderText(_translate("loginForm", "用户名"))
        self.passwordL.setPlaceholderText(_translate("loginForm", "密码"))
        self.loginL.setText(_translate("loginForm", "登录"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loginForm = QtWidgets.QWidget()
    ui = Ui_loginForm()
    ui.setupUi(loginForm)
    loginForm.show()
    sys.exit(app.exec_())